### PR TITLE
Allow file to be executed form anywhere in the system

### PR DESCRIPTION
**Pull request by Thunder33345**
I proposed this change for users who like to have these commands installed inside their PATH variable, currently it would only work IF there's phartools.php inside your current directory or else it would return "Could not open input file: phartools.php"
with this change it allows the script to be executed form anywhere as long as there's a phartools.php resides in the same directory of the batch script

### CODE REVIEW

**Comment by Thunder33345** [comment]
Temporarily closed will undergo more testing...

**Comment by Thunder33345** [comment]
this should fully work for now on without issues if you like to have scripts in your window %PATH%

**Comment by Thunder33345** [comment]
closed due to inactivity

**Comment by legoboy0215** [comment]
lmao

**Comment by Thunder33345** [comment]
/shrug
oh well

**Comment by Thunder33345** [comment]
this also dosent deal with compressed phars properly AFAIK

**Comment by Flavius12** [comment]
The PHP script and the Windows Batch file MUST ALWAYS be on the same directory.
(Sorry for the late reply)

**Comment by Thunder33345** [comment]
by that i meant like keeping the bash+php in a bin directory by adding it to evn path

so i can run phartools not C://Path/to/phartools.cmd

**Comment by Flavius12** [comment]
Oh ok

**Pull request closed without merging**
